server:
  port: 8090

spring:
  datasource:
    url: "jdbc:h2:mem:MyDb"
    driverClassName: "org.h2.Driver"
    username: "aaa"
    password: "ppp"
  sql:
    init:
      platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

application:
  usecase:
    newFlowEnabled : false
    feature:
      carLoan:
        isEnabled: true
      homeLoan:
        isEnabled: true
  interfaceadapters:
    feature:
      someFeature:
        someName: true

